name: "Win32 Platform Build (Temporary test CI)"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install LLVM Tools
      run: choco install llvm -y

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: c-export-symbols
        path: build/Release/c-export-symbols.exe