name: Multi-platform Build

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: ${{ matrix.os }} - ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

        build_type:
          - Release

    steps:
      - uses: actions/checkout@v4

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v2
        with:
            version: "18"

      - name: Configure
        run: >
          cmake
          -B build
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: c-export-symbols-${{ runner.os }}
          path: |
            build/c-export-symbols
            build/Release/c-export-symbols.exe